### ISSUE TITLE
I don't get how to indicate direction

### ISSUE THREAD

**Issue by j2l** [PaulMaly/svelte-ticker#6]
Hi,
The repl is too complicated for me.
You state that props can be applied to Ticker, I tried:
```
<script>
	import Ticker from 'svelte-ticker'
	let props = {
		direction: 'top',
		duration: 1,
		delay: 0,
		loop: true,
		pausing: true,
		alternate: false,
		behavior: 'auto'
	};
...
<Ticker {...props}>
long content
</Ticker>
```
but it's not working.
Would you please give a working basic example in the readme to get how to tell the props to the ticker?
Thanks!

**Comment by PaulMaly** [comment]
@j2l Hi! Yea, sure check this one [REPL](https://svelte.dev/repl/6160752301ac4dddb7ffdc0984e4a850?version=3.46.2).

Feel free to ask if any questions still remain!

**Comment by j2l** [comment]
Thank you!
Very informative and simple :)
